##
# List avaliable serialports
http://127.0.0.1/serialport/api

###
# set intrval for periodic write
GET http://127.0.0.1/serialport/api/interval/COM1

###
# set intrval for periodic write
POST http://127.0.0.1/serialport/api/interval/COM1
content-type: application/json

{
    "buff": "PFB"
}

###
# unset intrval for periodic write
DELETE http://127.0.0.1/serialport/api/interval/COM1/3v9mfrtd04jp17gw64