##
# List avaliable serialports
http://127.0.0.1/serialport/api

###
# Open port
POST http://127.0.0.1/serialport/api/COM6
content-type: application/json

{
    "baudRate": 38400
}

###
# Get port status
http://127.0.0.1/serialport/api/COM6

###
# Close port
DELETE http://127.0.0.1/serialport/api/COM6


###
# Write buffer
PUT http://127.0.0.1/serialport/api/COM6
content-type: application/json

{
    "buff": "MH"
}


###
# get intrval for periodic write
GET http://127.0.0.1/serialport/api/interval/COM5

###
# set intrval for periodic write
POST http://127.0.0.1/serialport/api/interval/COM6/PFB
content-type: application/json

{
    "interval": 2000
}

###
# unset intrval for periodic write
DELETE http://127.0.0.1/serialport/api/interval/COM6/PFB